apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  volumes:
    - name: vol-filestore
      persistentVolumeClaim:
        claimName: pvc-filestore
    - name: vol-standard
      persistentVolumeClaim:
        claimName: pvc-standard
  containers:
    - name: ubuntu
      image: ubuntu:latest
      command: ["/bin/sleep", "3650d"]
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/my_filestore"
          name: vol-filestore
        - mountPath: "/my_standard"
          name: vol-standard

  restartPolicy: Always

