kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-filestore
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: storageclass-filestore
  resources:
    requests:
      storage: 30Gi